version: '3.8'

services:
  fastapi:
    build: 
      context: ./chatservice/src/
      dockerfile: docker/Dockerfile
    container_name: fastapi-chatservice
    ports:
      - "8000:8000"
    command: python3 main.py

  redis:
    image: redis:7.4
    command: "redis-server  --enable-debug-command yes --protected-mode no"
    ports:
      - "16385:6379"
      - "6379:6379"
    volumes:
      - ./configs/redis/sysctl.conf:/etc/sysctl.conf
    
  redis_exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
      
