version: '3.8'

services:
  fastapi:
    build: 
      context: ./chatservice/src/
      dockerfile: docker/Dockerfile
    container_name: fastapi-chatservice
    ports:
      - "8000:8000"
    command: python3 main.py

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./configs/redis/sysctl.conf:/etc/sysctl.conf
    
  redis_exporer:
    image: oliver006/redis_exporer
    container_name: redis_exporer
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
      
