version: '3.8'

services:
  fastapi:
    build: 
      context: ./chatservice/
      dockerfile: src/docker/Dockerfile
    container_name: fastapi-chatservice
    volumes:
      - .chatservice/src:/opt/pysetup/src
    ports:
      - "8000:8000"
    command: python3 main.py

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
