receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  # prometheus:
  #   endpoint: "0.0.0.0:9464"
  #   namespace: default

  # prometheusremotewrite:
  #   endpoint: http://prometheus:9090/api/v1/write
  #   tls:
  #     insecure: true

  debug:
    verbosity: detailed

extensions:
  pprof:
  health_check:
  zpages:
    endpoint: "0.0.0.0:55679" 

service:
  extensions: [pprof, health_check, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug]
    traces:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]