receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  resource:
    attributes:
    - action: insert
      key: service_name
      from_attribute: service.name
    - action: insert
      key: service_namespace
      from_attribute: service.namespace
    - action: insert
      key: compose_service
      from_attribute: compose_service
    - action: insert
      key: loki.resource.labels
      value: service_name, service_namespace, compose_service

exporters:
  otlphttp/loki:
    auth:
      authenticator: basicauth/loki
    endpoint: http://loki:3100/otlp/v1/logs
  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true
      insecure_skip_verify: true 
  debug:
    verbosity: detailed

extensions:
  basicauth/loki:
    client_auth:
      username: admin
      password: admin
  pprof:
  health_check:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [pprof, health_check, zpages, basicauth/loki]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug]
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo, debug]
    logs:
      receivers: [otlp]
      processors: [resource]
      exporters: [otlphttp/loki, debug]