global:
  scrape_interval: 5s  # 메트릭 수집 주기

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus 자체 메트릭 수집
  - job_name: 'fastapi-chatservice'
    scrape_interval: 5s
    static_configs:
      - targets: ['fastapi-chatservice:8000']
# remote_write:
#   - url: 'http://otel-collector:4317/v1/metrics'  # OpenTelemetry Collector 메트릭 수신 엔드포인트
