global:
  scrape_interval: 5s  # 메트릭 수집 주기

scrape_configs:
  - job_name: 'node_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['172.16.153.128:9100']  # Node Exporter 실행 중인 서버의 IP와 포트
  - job_name: 'chatservice'
    scrape_interval: 10s
    static_configs:
      - targets: ['172.16.153.128:8000']

# remote_write:
#   - url: 'http://otel-collector:4317/v1/metrics'  # OpenTelemetry Collector 메트릭 수신 엔드포인트
